# Generated by Django 4.1.7 on 2023-03-23 13:08

from django.db import migrations, models
import product.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productimagemodel',
            name='image',
            field=models.ImageField(upload_to=product.models.productpath),
        ),
    ]
