# Generated by Django 4.1.7 on 2023-03-23 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_id_alter_product_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='uid',
        ),
    ]
